### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by daspartho**
Hello, @mrdbourke

Spotted this minor repetition typo in Ch 2 exercise and solution notebook. Made a quick fix.

Also, fantastic course :)

### CODE REVIEW

**Comment by daspartho** [comment]
Spotted another typo in chapter 3, fixed!

**Comment by daspartho** [comment]
fixed minor typo in ch 6

**Comment by daspartho** [comment]
fixed minor typo in ch 2

**Comment by daspartho** [comment]
fixed spell typo in ch 8

**Comment by mrdbourke** [comment]
Thank you so much!

You're better than a spellchecker hahaha!

I read so much of my own stuff/code I often glaze over simple typos.

**Pull request merged**
