### PR TITLE
Fix #105

### LINKED ISSUE #105: Innacuracy regarding from/to_numpy() in Notebook 00
It's not super clear, but I feel the notebook implies that to/from_numpy() creates a copy of the tensor/array instead of a view (which they do).

### PR DESCRIPTION
**Pull request by xl0**
I've also added a cell explaining related type() behavior.

### CODE REVIEW

**Comment by xl0** [comment]
Made a mistake regarding type() behaviour. Force-pushed a fix just now,

**Comment by mrdbourke** [comment]
Thank you for this!

However, I don't get the same results that you're demonstrating 🤔 

See this example short notebook: https://colab.research.google.com/drive/1WJcr3WgHxPxhBUL2_v1UR59woCyEPudI?usp=sharing 

```python

# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

>>> (array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))
```

```python
# Change the array, keep the tensor
array = array + 1
array, tensor

>>> (array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))
```

More examples in the notebook.

**Comment by xl0** [comment]
Yes, you are re-assigning the array, I did +=.

I assume the point was to demonstrate that array and tensor share / don't share memory, right?

**Comment by xl0** [comment]
https://github.com/mrdbourke/pytorch-deep-learning/blob/064181a18a10ef61abf23c97313a49aea1de41ee/00_pytorch_fundamentals.ipynb

Under "PyTorch tensors & NumPy"

**Comment by xl0** [comment]
Got you.

**Pull request closed without merging**
